export enum Category {
  FICTION = 'Ficção',
  FICTION_CLASSICS = 'Clássicos',
  FICTION_ACTION_ADVENTURE = 'Ação e Aventura',
  FICTION_FANTASY = 'Fantasia',
  FICTION_HORROR = 'Terror',
  FICTION_MISTERY = 'Mistério e Detetive',
  FICTION_ROMANCE = 'Romance',
  FICTION_SCIENTIFIC = 'Ficção Científica',
  FICTION_DISTOPY = 'Distopia',
  FICTION_THRILLER = 'Thriller',
  BIOGRAPHY = 'Biografia',
  COMICS = 'Quadrinhos',
  JUVENILE_FICTION = 'Juvenil',
  YOUNG_ADULT_FICTION = 'Young Adult',
  EDUCATION = 'Educação',
  RELIGION = 'Religião',
  SELF_HELP = 'Autoajuda',
  MISCELLANEOUS = 'Diversos',
}
